// GET /api/financial-aid/worksheet
//
// Returns a print-ready HTML worksheet that mirrors the 7-step
// wizard. Parents print it, gather their statements at the dining
// table, then fill out the online form with everything in hand.
//
// Mirrors the structure of FAST's worksheet PDF (the inspiration for
// this build), but with our plain-language labels, our "Why we ask"
// blocks, and grouped by step number.

import { NextResponse } from 'next/server';
import { WIZARD_SECTIONS } from '@/lib/financial-aid/wizard-schema';

export const dynamic = 'force-dynamic';

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]!));
}

export async function GET() {
  const sections = WIZARD_SECTIONS;

  const body = sections.map((sec) => {
    if (sec.key === 'students') {
      return `<section>
  <h2>Step ${sec.step}. ${escapeHtml(sec.title)}</h2>
  <p class="why"><strong>Why we ask:</strong> ${escapeHtml(sec.why)}</p>
  <p>You&rsquo;ll do this online — log in and the wizard will list your kids. Check each one attending and enter their tuition + the aid you&rsquo;re requesting per student.</p>
</section>`;
    }
    const fields = sec.fields.map((f) => {
      const help = f.help ? `<span class="help">${escapeHtml(f.help)}</span>` : '';
      return `<div class="row"><label>${escapeHtml(f.label)}${f.required ? ' *' : ''}</label>${help}<div class="blank">___________________________________</div></div>`;
    }).join('\n');
    const explanation = sec.optionalExplanationKey
      ? `<div class="row"><label>Anything else about this section? (optional)</label><div class="blank" style="height:48px">________________________________________________________________</div></div>`
      : '';
    return `<section>
  <h2>Step ${sec.step}. ${escapeHtml(sec.title)}</h2>
  <p class="why"><strong>Why we ask:</strong> ${escapeHtml(sec.why)}</p>
  ${sec.intro ? `<p class="intro">${escapeHtml(sec.intro)}</p>` : ''}
  ${fields}
  ${explanation}
</section>`;
  }).join('\n\n');

  const html = `<!doctype html>
<html><head><meta charset="utf-8">
<title>Financial Aid Worksheet</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 760px; margin: 56px auto; padding: 0 48px; color: #0f172a; line-height: 1.5; }
  h1 { font-size: 22px; margin: 0 0 4px; color: #047857; }
  h2 { font-size: 15px; margin: 28px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #d1fae5; color: #047857; }
  .why { background: #f0fdf4; border-left: 3px solid #10b981; padding: 8px 12px; font-size: 12px; color: #064e3b; margin: 6px 0 12px; }
  .intro { font-size: 13px; color: #334155; margin: 0 0 12px; }
  .row { margin: 8px 0; }
  label { font-size: 13px; font-weight: 600; color: #0f172a; display: block; }
  .help { font-size: 11px; color: #64748b; display: block; margin: 2px 0 6px; font-weight: normal; }
  .blank { font-size: 13px; color: #94a3b8; letter-spacing: 1px; margin-top: 2px; }
  .topnote { background: #eff6ff; border-radius: 6px; padding: 12px 16px; font-size: 12px; color: #1e40af; margin: 0 0 24px; }
  button { background: #047857; color: #fff; border: 0; padding: 6px 12px; border-radius: 4px; cursor: pointer; font: inherit; }
  @media print { body { margin: 0; padding: 0.4in; } .noprint { display: none; } .topnote { background: #fff; border: 1px dashed #94a3b8; } }
  .noprint { background: #f1f5f9; border-radius: 6px; padding: 10px 14px; font-size: 12px; color: #475569; margin-bottom: 24px; }
</style></head>
<body>
  <div class="noprint">
    Use this worksheet to gather what you&rsquo;ll need before filling out the online application. <button onclick="window.print()">Print this worksheet</button>
  </div>
  <h1>Financial Aid Worksheet</h1>
  <p class="topnote">
    <strong>How to use this:</strong> Fill in what you can with your tax return, statements, and household records. Then log into the parent portal and enter the answers into the online application. The wizard saves as you go, so you can stop and resume anytime.
  </p>
  ${body}
  <p style="margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #888;">
    Generated by Growth Suite · Save this as your record copy.
  </p>
</body></html>`;
  return new NextResponse(html, {
    status: 200,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  });
}
